**IMPORT LIBRARY**
- numpy: Digunakan untuk melakukan komputasi numerik berbasis array/matrix.
- pandas: Digunakan untuk mengelola data dalam bentuk tabel (DataFrame), termasuk untuk mengimpor dataset.
- matplotlib.pyplot: Digunakan untuk membuat visualisasi data dalam bentuk grafik atau plot.


In [45]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 

LUKMANUL HAKIM
A11.2022.14197
DATA MINING A11.4509

**IMPORT DATA**
- pd.read_csv(): Mengimpor dataset dari file CSV.
- dataset.iloc[:, :-1]: Mengambil semua kolom kecuali kolom terakhir sebagai variabel fitur (X).
- dataset.iloc[:, -1]: Mengambil kolom terakhir sebagai variabel target (Y).

In [46]:
dataset = pd.read_csv('dataset/kindey_stone_urine_analysis_modified.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [47]:
print(x)

[[1.021e+00       nan 7.250e+02 1.400e+01 4.430e+02 2.450e+00]
 [1.017e+00 5.740e+00       nan 3.000e+02 2.960e+02 4.490e+00]
 [1.008e+00 7.200e+00 3.210e+02 1.490e+01 1.010e+02 2.360e+00]
 [1.011e+00 5.510e+00 4.080e+02 1.260e+01 2.240e+02 2.150e+00]
 [1.005e+00 6.520e+00 1.870e+02 7.500e+00 1.820e+03 1.160e+00]
 [1.020e+00 5.270e+00 6.680e+02 2.530e+01 2.520e+02 3.340e+00]
 [1.012e+00 5.620e+00 4.610e+02 1.740e+01 1.950e+02       nan]
 [1.029e+00 5.670e+00 1.107e+03 3.590e+01 5.500e+02       nan]
 [1.015e+00 5.410e+00 5.430e+02 2.190e+01 1.700e+02 1.160e+00]
 [1.021e+00 6.130e+00 7.790e+02 2.570e+01 3.820e+02 2.210e+00]
 [1.011e+00       nan 3.450e+02 1.150e+01 1.520e+02 1.930e+00]
 [1.025e+00 5.530e+00 9.070e+02 2.840e+01 8.960e+03 1.270e+00]
 [1.006e+00 7.120e+00 2.420e+02 1.130e+01 6.400e+01       nan]
 [1.007e+00 5.350e+00 2.830e+02 9.900e+00 1.470e+02       nan]
 [1.011e+01 5.210e+00 4.500e+02 1.790e+01 1.610e+02 1.530e+00]
 [1.018e+00 4.900e+00 6.840e+02 2.610e+01 2.840e+02 5.0

In [48]:
print(y)

['no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes'
 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' nan 'yes' 'yes'
 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes'
 'yes']


**MENGATASI MISSING VALUES**
- SimpleImputer(): Digunakan untuk mengisi missing values. Pada bagian ini, kita mengisi nilai yang hilang pada kolom 1 hingga 5 di variabel X dengan mean.

In [49]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:6])
x[:, 1:6] = imputer.transform(x[:, 1:6])

In [50]:
print(x)

[[1.02100000e+00 6.00507042e+00 7.25000000e+02 1.40000000e+01
  4.43000000e+02 2.45000000e+00]
 [1.01700000e+00 5.74000000e+00 6.07788732e+02 3.00000000e+02
  2.96000000e+02 4.49000000e+00]
 [1.00800000e+00 7.20000000e+00 3.21000000e+02 1.49000000e+01
  1.01000000e+02 2.36000000e+00]
 [1.01100000e+00 5.51000000e+00 4.08000000e+02 1.26000000e+01
  2.24000000e+02 2.15000000e+00]
 [1.00500000e+00 6.52000000e+00 1.87000000e+02 7.50000000e+00
  1.82000000e+03 1.16000000e+00]
 [1.02000000e+00 5.27000000e+00 6.68000000e+02 2.53000000e+01
  2.52000000e+02 3.34000000e+00]
 [1.01200000e+00 5.62000000e+00 4.61000000e+02 1.74000000e+01
  1.95000000e+02 4.18028169e+00]
 [1.02900000e+00 5.67000000e+00 1.10700000e+03 3.59000000e+01
  5.50000000e+02 4.18028169e+00]
 [1.01500000e+00 5.41000000e+00 5.43000000e+02 2.19000000e+01
  1.70000000e+02 1.16000000e+00]
 [1.02100000e+00 6.13000000e+00 7.79000000e+02 2.57000000e+01
  3.82000000e+02 2.21000000e+00]
 [1.01100000e+00 6.00507042e+00 3.45000000e+02 1.1

Cara yang tepat untuk mengimputasi data target adalah menggunakan metode yang kompatibel dengan LabelEncoder. Saat kita mencoba menggunakan y[:, np.newaxis], ini akan menghasilkan masalah karena y seharusnya tetap berbentuk 1D array (bukan 2D array).

In [51]:
# imputerY = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
# imputerY.fit(y[:, np.newaxis])
# y[:, np.newaxis] = imputerY.transform(y[:, np.newaxis])
# print(y)

y = y.reshape(-1, 1)  # Ubah y menjadi array 2D
imputerY = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
y = imputerY.fit_transform(y).ravel()  # Gunakan ravel() untuk mengubah kembali ke array 1D
print(y)


['no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no' 'no'
 'no' 'no' 'no' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes'
 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'no' 'yes' 'yes'
 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes' 'yes'
 'yes']


In [52]:
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
# ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
# x = np.array(ct.fit_transform(x))
# print(x) 

**LABEL ENCODING UNTUK Y**
- LabelEncoder(): Digunakan untuk mengubah variabel kategorikal menjadi angka. Ini akan mengubah no dan yes di variabel target menjadi 0 dan 1.

In [53]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1]


**TEST TRAIN SPLIT**
- train_test_split(): Membagi dataset menjadi data latih (train) dan data uji (test). Di sini, kita membagi 80% data sebagai training set dan 20% sebagai testing set.
- random_state memastikan bahwa pembagian data konsisten setiap kali kode dijalankan.

In [87]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [55]:
print(x_train)

[[1.00900000e+00 6.37000000e+00 3.25000000e+02 1.22000000e+01
  9.70000000e+01 1.19000000e+00]
 [1.00800000e+00 7.20000000e+00 3.21000000e+02 1.49000000e+01
  1.01000000e+02 2.36000000e+00]
 [1.02000000e+00 5.66000000e+00 7.02000000e+02 2.36000000e+01
  3.30000000e+02 3.98000000e+00]
 [1.00800000e+00 5.94000000e+00 2.56000000e+02 8.10000000e+00
  1.30000000e+02 4.18028169e+00]
 [1.02100000e+00 5.94000000e+00 7.74000000e+02 2.79000000e+01
  3.25000000e+02 6.96000000e+00]
 [1.01800000e+00 4.90000000e+00 6.84000000e+02 2.61000000e+01
  2.84000000e+02 5.09000000e+00]
 [1.01400000e+01 5.90000000e+00 4.56000000e+02 2.67000000e+02
  1.64000000e+02 6.99000000e+00]
 [1.03100000e+00 5.73000000e+00 6.07788732e+02 2.61000000e+02
  5.16000000e+02 3.01000000e+00]
 [1.01400000e+00 6.14000000e+00 5.65000000e+02 2.36000000e+01
  2.14000000e+02 1.45000000e+00]
 [1.02600000e+00 6.19000000e+00 9.56000000e+02 2.76000000e+01
  4.73000000e+02 5.67000000e+00]
 [1.02400000e+00 5.40000000e+00 8.03000000e+02 2.1

In [56]:
print(x_test)

[[1.03300000e+00 5.58000000e+00 1.03200000e+03 2.91000000e+01
  4.30000000e+02 8.94000000e+00]
 [1.01000000e+00 6.61000000e+00 2.25000000e+02 9.80000000e+00
  7.20000000e+01 1.70000000e-01]
 [1.01900000e+00 6.00507042e+00 5.79000000e+02 1.55000000e+01
  2.97000000e+02 3.93000000e+00]
 [1.02600000e+00 6.29000000e+00 8.33000000e+02 2.22000000e+01
  4.57000000e+02 4.45000000e+00]
 [1.02400000e+00 5.77000000e+00 6.98000000e+02 1.95000000e+01
  7.08000000e+03 1.30000000e+01]
 [1.02400000e+00 5.60000000e+00 8.66000000e+02 2.95000000e+01
  3.60000000e+02 5.54000000e+00]
 [1.01100000e+00 7.01000000e+00 6.07788732e+02 2.14000000e+01
  1.24000000e+02 1.27000000e+00]
 [1.02500000e+00 7.90000000e+00 7.21000000e+02 2.36000000e+01
  3.01000000e+02 9.04000000e+00]
 [1.01800000e+00 6.18000000e+00 6.94000000e+02 2.33000000e+01
  3.11000000e+02 5.64000000e+00]
 [1.02200000e+00 5.09000000e+00 7.36000000e+02 1.98000000e+01
  4.18000000e+02 8.53000000e+00]
 [1.02300000e+00 5.85000000e+00 9.70000000e+02 3.8

In [57]:
print(y_train)

[0 0 0 0 1 0 1 1 0 1 1 1 0 1 1 0 0 1 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 1 1 0 0
 0 0 1 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0]


In [58]:
print(y_test)

[0 0 0 1 1 1 1 1 0 1 0 1 0 0 1 0]


**STANDARDISASI FITUR**
- StandardScaler(): Digunakan untuk menstandarkan fitur numerik agar memiliki distribusi normal dengan mean 0 dan standard deviation 1. Di sini, kuta melakukan scaling pada kolom ke-1 hingga ke-5.

In [59]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 1:6] = sc.fit_transform(x_train[:, 1:6])
x_test[:, 1:6] = sc.transform(x_test[:, 1:6])

In [60]:
print(x_train)

[[ 1.00900000e+00  6.15823385e-01 -1.22669716e+00 -3.75544963e-01
  -3.13587193e-01 -9.56658349e-01]
 [ 1.00800000e+00  1.95478266e+00 -1.24601339e+00 -3.26523247e-01
  -3.10142832e-01 -5.36303905e-01]
 [ 1.02000000e+00 -5.29551416e-01  5.93857457e-01 -1.68564384e-01
  -1.12953169e-01  4.57253259e-02]
 [ 1.00800000e+00 -7.78543116e-02 -1.55990212e+00 -4.49985347e-01
  -2.85171215e-01  1.17681991e-01]
 [ 1.02100000e+00 -7.78543116e-02  9.41549586e-01 -9.04927622e-02
  -1.17258620e-01  1.11637169e+00]
 [ 1.01800000e+00 -1.75558641e+00  5.06934425e-01 -1.23173906e-01
  -1.52563320e-01  4.44523132e-01]
 [ 1.01400000e+01 -1.42382469e-01 -5.94090651e-01  4.25065254e+00
  -2.55894147e-01  1.12715001e+00]
 [ 1.03100000e+00 -4.16627140e-01  1.38905843e-01  4.14171539e+00
   4.72096136e-02 -3.02773658e-01]
 [ 1.01400000e+00  2.44786478e-01 -6.77233999e-02 -1.68564384e-01
  -2.12839636e-01 -8.63246250e-01]
 [ 1.02600000e+00  3.25446675e-01  1.82043802e+00 -9.59396195e-02
   1.01827337e-02  6.5290

In [61]:
print(x_test)

[[ 1.03300000e+00 -6.58607732e-01  2.18744638e+00 -6.87053328e-02
  -2.68441462e-02  1.82774075e+00]
 [ 1.01000000e+00  1.00299233e+00 -1.70960290e+00 -4.19119822e-01
  -3.35114449e-01 -1.32312120e+00]
 [ 1.01900000e+00  2.71175508e-02 -1.16596958e-04 -3.15629532e-01
  -1.41369147e-01  2.77614608e-02]
 [ 1.02600000e+00  4.86767069e-01  1.22646397e+00 -1.93983052e-01
  -3.59471001e-03  2.14585658e-01]
 [ 1.02400000e+00 -3.52098982e-01  5.74541228e-01 -2.43004768e-01
   5.69940588e+00  3.28640660e+00]
 [ 1.02400000e+00 -6.26343653e-01  1.38582286e+00 -6.14428564e-02
  -8.71204623e-02  6.06197918e-01]
 [ 1.01100000e+00  1.64827391e+00  1.38905843e-01 -2.08508005e-01
  -2.90337757e-01 -9.27916165e-01]
 [ 1.02500000e+00  3.08402542e+00  6.85609547e-01 -1.68564384e-01
  -1.37924786e-01  1.86366848e+00]
 [ 1.01800000e+00  3.09314635e-01  5.55224998e-01 -1.74011241e-01
  -1.29313884e-01  6.42125649e-01]
 [ 1.02200000e+00 -1.44907767e+00  7.58045407e-01 -2.37557910e-01
  -3.71772290e-02  1.6804

In [89]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Inisialisasi model
classifier = LogisticRegression(random_state=0)

# 2. Latih model dengan data training
classifier.fit(x_train, y_train)

# 3. Prediksi dengan data uji
y_pred = classifier.predict(x_test)



c:\Users\ASUS\miniconda3\envs\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [91]:
print("Accuracy Logistic Regression:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy Logistic Regression: 0.6875
Confusion Matrix:
 [[6 2]
 [3 5]]
Classification Report:
               precision    recall  f1-score   support

           0       0.67      0.75      0.71         8
           1       0.71      0.62      0.67         8

    accuracy                           0.69        16
   macro avg       0.69      0.69      0.69        16
weighted avg       0.69      0.69      0.69        16



In [70]:
print(np.bincount(y))


[46 33]


In [97]:
from sklearn.ensemble import RandomForestClassifier

classifier_rf = RandomForestClassifier(n_estimators=35, random_state=0)
classifier_rf.fit(x_train, y_train)
y_pred_rf = classifier_rf.predict(x_test)

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))


Random Forest Accuracy: 0.875
Confusion Matrix:
 [[6 2]
 [3 5]]
Classification Report:
               precision    recall  f1-score   support

           0       0.67      0.75      0.71         8
           1       0.71      0.62      0.67         8

    accuracy                           0.69        16
   macro avg       0.69      0.69      0.69        16
weighted avg       0.69      0.69      0.69        16

